name: lintorium_example

version: '1.0.0'

license: 'BSD-3-Clause'

repository: https://github.com/ilexbor/lintorium

issue_tracker: https://github.com/ilexbor/lintorium/issues

dev_dependencies:
  lintorium:
    path: '..'

environment:
  sdk: '>=3.11.0 <4.0.0'

publish_to: none