name: lintorium

version: '301.0.0'

license: 'BSD-3-Clause'

description: >
  The strictest linting rules for Dart code. 
  Perfect for perfectionists, whether solo developers or entire teams striving for flawless code.

repository: https://github.com/ilexbor/lintorium

issue_tracker: https://github.com/ilexbor/lintorium/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - analysis-options
  - analyzer-diagnostics
  - code-style
  - linter-rules
  - lints