name: lintorium_cli

version: '1.0.0'

license: 'BSD-3-Clause'

repository: https://github.com/ilexbor/lintorium

issue_tracker: https://github.com/ilexbor/lintorium/issues

dependencies:
  collection: ^1.18.0
  interact: ^2.2.0
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  lintorium:
    path: '..'

environment:
  sdk: '>=3.11.0 <4.0.0'

publish_to: none